name: Invicti Scan

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: invicti/scan-cli:latest
    env:
      INVICTI_API_BASE_URL: "https://platform.invicti.com"
      INVICTI_API_TOKEN: xyURkadsNInTgxOEE14mw8nUrKtivkr8kEDeK72X6hk
      INVICTI_TARGET_ID: "1060c242-2e5b-4156-91a5-02d364fea51b"
      INVICTI_SCAN_AGENT: "CloudAgent"
      INVICTI_SCAN_PROFILE: "Full Scan"

    steps:
      - name: Run Invicti Scan CLI
        run: /home/invicti/scancli/ScanCLI

      - name: Upload scan artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: invicti-scan-results
          path: |
            ./scan-results/**
            ./reports/**
            ./*.json
            ./*.html
          if-no-files-found: ignore
          retention-days: 7
